class InnerError(Exception):
    pass


class UnsupportError(Exception):
    pass
